/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness/readiness check
         * @description Reports whether the database is reachable. Intended for load-balancer and orchestrator health probes, not for consumers of the data endpoints below.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/worlds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every world known to Realty
         * @description Returns every row of the RealtyWorld table. Always 200; an empty array means no world has ever been registered.
         */
        get: operations["listWorlds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/region": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up a single region
         * @description The HTTP form of the in-game `/realty info` command.
         */
        get: operations["getRegion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/region/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One region's history
         * @description The HTTP form of `/realty history`, which is granted by default and accepts any region. Also answers the questions that would otherwise want routes of their own: a region's price history is `type=BUY`, and who has rented it before is `type=RENT`. A region nobody has traded is a 200 with an empty `entries` array, not a 404.
         */
        get: operations["getRegionHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every registered region
         * @description A page of every region Realty has registered, whether or not it carries a contract, in a fixed total order (WorldGuard region id, then world id, then internal row id) so that paging cannot repeat or skip a row. Entries are identity only -- use `/v1/region` for one region's full state, or `/v1/regions/search` to browse what is actually on the market.
         */
        get: operations["listRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/regions/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search regions by type, world, price, tags and occupancy
         * @description The bulk browse endpoint, backed by the same query as the in-game `/realty search` dialog. Every filter is optional; with none given it returns every region carrying a contract, most expensive first. A result carries only identity, contract type and price -- fetch `/v1/regions` for a single region's full state. No match is a 200 with an empty `results` array, never a 404.
         */
        get: operations["searchRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A server-wide feed of recent events
         * @description Recent events across every region, newest first. Each event is individually obtainable in game -- `/realty history` is granted by default and accepts any region -- but no command performs the sweep across regions, so this is the aggregation the v1.x spec flags rather than plainly public data. The default type set is the sales-and-lettings ticker (`BUY`, `AUCTION_BUY`, `OFFER_BUY`, `RENT`); naming types explicitly gives the full audit trail.
         */
        get: operations["getActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auctions currently taking bids
         * @description The browse form of `/realty auction info`, which is granted by default and already renders the auctioneer, minimum bid, minimum step and bidding duration to any player. `endDate` is computed in SQL as the last bid -- or the start, where there is none -- plus the bidding duration, which is also what `ending_soon` orders by, so paging cannot put an auction closing sooner on a later page.
         */
        get: operations["listAuctions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leaderboard/owners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Title holders ranked by plot count
         * @description Owners ranked highest first. Ownership is already public per player via `/realty list <player>`, so no row reveals anything new; what this route adds is the ranking, which no in-game command performs. Ties break on the title holder's UUID so the order is total and paging cannot repeat or skip an owner.
         */
        get: operations["getOwnersLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-wide totals
         * @description Aggregates over the whole estate: region and contract counts, occupancy, mean prices and the mean lease term. No player or region identity appears in the response. An empty server reports zeroes rather than nulls or absent fields, so a dashboard need not distinguish "no data" from "nothing registered yet".
         */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every tag in use with its region count
         * @description Every tag id currently attached to at least one region, with how many regions carry it, so a consumer of `/v1/regions/search?tag=` can discover which values that filter accepts. Display names are deliberately absent -- they live in the plugin's RealtyTags config, which this service does not read, and the `tags` array on a region reports raw ids for the same reason. Always 200; an empty array means no tag is in use.
         */
        get: operations["listTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/regions/at": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Which registered regions contain a block
         * @description A point or column lookup, for a map click or a "what plot am I standing on" bot command. `y` is optional and the two forms are different questions rather than one with a default: with `y` this is a true point test at that block, so a region whose vertical band excludes the point does not match; without it, a column test matching every region whose horizontal footprint covers `(x, z)` at any height. The response's `test` field says which ran, so a consumer never has to infer it from whether it remembered to send `y`. `y` is deliberately not defaulted to the build floor or sea level, either of which would answer the column question wrongly on a server using vertical subdivision.
         *
         *     WorldGuard's answer is intersected with the regions Realty manages, so an unregistered WorldGuard region never appears. A block inside no registered region is a 200 with an empty `regions` array, never a 404.
         *
         *     Answered entirely by the query-service module, so an unreachable module is a 502 rather than a degraded response.
         */
        get: operations["regionsAt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/region/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A region's WorldGuard owners and members
         * @description The owner and member domains WorldGuard holds for the region, which are distinct from Realty's own title holder and tenant.
         *
         *     Each domain keeps WorldGuard's three kinds of entry apart rather than flattening them. `players` are UUID entries, named where the module could name them; `playerNames` are legacy name entries, which carry no id at all and which WorldGuard lower-cases on the way in; `groups` are permission groups, which are not players. A region configured the legacy way would otherwise report an empty owner list.
         *
         *     The region must be one Realty manages: an unregistered WorldGuard region is a 404 here rather than a pass-through. Answered entirely by the query-service module, so an unreachable module is a 502.
         */
        get: operations["regionMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/region/schematic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A region's captured schematic
         * @description The raw Sponge Schematic v3 bytes for the region, as captured in game by `/realty schematic capture`. Served as bytes rather than JSON because the browser-side renderers read an `ArrayBuffer` directly; base64 in JSON would cost a third more bytes and a decode step for nothing.
         *
         *     The schematic records block state only -- a stair's facing, a slab's half -- and deliberately not block entity NBT. Chests render as chests, but their contents are never captured and so are never served here.
         *
         *     Capturing is on demand, so a region Realty manages may legitimately have no schematic yet; that is a 404 rather than an empty body.
         */
        get: operations["regionSchematic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/resource-pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The resource pack for texturing previews
         * @description Where to fetch the resource packs a browser-side renderer should texture previews with, highest priority first, named by the query-service module's `resource-packs` setting.
         *
         *     Locations only -- the URLs -- never any pack's bytes. That URL is already public, since every joining player receives it, so reporting it redistributes nothing; serving the pack through this service would mean redistributing whatever assets it contains.
         *
         *     `url` is null when the operator has configured no pack, which is the default. That is a normal answer rather than an error, but note what it costs: without a pack a renderer does not draw blocks untextured, it does not draw most of them at all, because their block models carry no geometry. A plot then looks like a failed capture.
         *
         *     This is deliberately not server.properties' `resource-pack`. That pack is sent to the game client, which applies it over its own copy of the game, so it is usually an override pack; a browser has no vanilla assets underneath it. Name a pack that stands on its own.
         *
         *     Answered entirely by the query-service module, because the setting lives with the game server and not in this service's database. An unreachable module is therefore a 502 rather than an empty pack: "none configured" and "could not ask" are different answers.
         */
        get: operations["resourcePack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/worlds/geometry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every registered region's footprint in one world
         * @description For drawing a map overlay. The point of the route is that a page of regions costs the game server one main-thread hop rather than one per region, so a client should use this instead of looping `/v1/region`.
         *
         *     Unlike the other two module-backed routes, geometry here is enrichment rather than the whole answer: the region list comes from the database, so an unreachable module yields the page with every `dimensions` null rather than a 502 -- the same degradation `/v1/region` already applies. A `dimensions` of null therefore means either that, or a region Realty has registered which WorldGuard no longer holds.
         */
        get: operations["worldGeometry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a player's owned, landlorded and rented regions
         * @description The HTTP form of the in-game `/realty list` command. When `category` is `all` (the default), the three category lists -- owned, landlord and rented -- are paged against **one shared offset**, exactly as `/realty list` does in-game: the page boundary can fall inside a category rather than starting each category's own list at 1, so `owned`, `landlord` and `rented` on a given page are the slice of the combined, concatenated sequence that lands on that page, not independently-paged lists of their own length. When `category` is `owned` or `rented`, that single category is paged normally and returned under `regions` instead.
         */
        get: operations["listPlayerRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One player's holdings, as counts
         * @description The counts behind `/realty list <player>`, which accepts any target and is granted by default, so this exposes nothing a passer-by could not already enumerate in game. It exists because counting via that listing means paging it to the last page purely to read a total. A player holding nothing is a 200 with zeroes, not a 404: "nothing" is an answer, and there is no player resource here that could be missing.
         */
        get: operations["getPlayerSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve a player name to a UUID
         * @description Bare name-to-UUID resolution, so a client holding only a name can resolve once and cache the UUID rather than paying the module hop on every player-scoped call. This is the one route whose entire answer comes from the query-service module: there is no partial answer to degrade to, so an unreachable module is a 502 rather than a null name.
         */
        get: operations["lookupPlayer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * This document, as YAML
         * @description Serves the bundled openapi.yaml verbatim.
         */
        get: operations["getOpenApiYaml"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * This document, as JSON
         * @description The same document as `/v1/openapi.yaml`, parsed and re-serialised as JSON for tooling that prefers it.
         */
        get: operations["getOpenApiJson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Interactive API documentation
         * @description A self-contained Swagger UI page (assets loaded from a CDN) that renders `/v1/openapi.yaml`.
         */
        get: operations["getDocs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A world identity. `id` is always present and stable; `name` is null for a world id the RealtyWorld table has never seen. */
        WorldRef: {
            /** Format: uuid */
            id: string;
            name?: string | null;
        };
        /** @description A player identity. `id` is always present. */
        PlayerRef: {
            /** Format: uuid */
            id: string;
            /** @description From the query-service module; null when it is disabled or unreachable. */
            name?: string | null;
        };
        PlayerSummaryResponse: {
            player: components["schemas"]["PlayerRef"];
            titleHeld: number;
            landlordOf: number;
            /** @description The subset of `landlordOf` that currently has a tenant, so a caller can show let versus vacant without a second call. */
            occupiedLandlordOf: number;
            renting: number;
            authorityOver: number;
        };
        HistoryResponse: {
            page: number;
            pageSize: number;
            totalCount: number;
            totalPages: number;
            entries: components["schemas"]["HistoryResponse_Entry"][];
        };
        /** @description One event. `kind` decides which of the remaining fields are present; the others are omitted rather than sent as null, so a consumer cannot mistake "this kind has no such field" for "this field happened to be empty". Switch on `kind`: freehold carries buyer, authority and price; leasehold carries tenant, landlord and the lease terms; agent carries agent and actor. */
        HistoryResponse_Entry: {
            /** @enum {string} */
            kind: "freehold" | "leasehold" | "agent";
            eventType: string;
            /** Format: date-time */
            eventTime: string;
            buyer?: components["schemas"]["PlayerRef"];
            authority?: components["schemas"]["PlayerRef"];
            tenant?: components["schemas"]["PlayerRef"];
            landlord?: components["schemas"]["PlayerRef"];
            agent?: components["schemas"]["PlayerRef"];
            actor?: components["schemas"]["PlayerRef"];
            price?: number;
            /** Format: int64 */
            durationSeconds?: number;
            extensionsRemaining?: number;
        };
        ActivityResponse: {
            page: number;
            pageSize: number;
            totalCount: number;
            totalPages: number;
            events: components["schemas"]["ActivityResponse_Event"][];
        };
        /** @description The same polymorphic shape as HistoryResponse_Entry, with the region and world added since a server-wide feed must say where each event happened. `kind` decides which party and detail fields are present; the others are omitted rather than sent as null. */
        ActivityResponse_Event: {
            /** @enum {string} */
            kind: "freehold" | "leasehold" | "agent";
            eventType: string;
            /** Format: date-time */
            eventTime: string;
            worldGuardRegionId: string;
            world: components["schemas"]["WorldRef"];
            buyer?: components["schemas"]["PlayerRef"];
            authority?: components["schemas"]["PlayerRef"];
            tenant?: components["schemas"]["PlayerRef"];
            landlord?: components["schemas"]["PlayerRef"];
            agent?: components["schemas"]["PlayerRef"];
            actor?: components["schemas"]["PlayerRef"];
            price?: number;
            /** Format: int64 */
            durationSeconds?: number;
            extensionsRemaining?: number;
        };
        AuctionsResponse: {
            page: number;
            pageSize: number;
            totalCount: number;
            totalPages: number;
            auctions: components["schemas"]["AuctionsResponse_Entry"][];
        };
        AuctionsResponse_Entry: {
            worldGuardRegionId: string;
            world: components["schemas"]["WorldRef"];
            auctioneer: components["schemas"]["PlayerRef"];
            /** Format: date-time */
            startDate: string;
            /**
             * Format: date-time
             * @description When bidding closes.
             */
            endDate: string;
            minBid: number;
            minStep: number;
            /** Format: int64 */
            biddingDurationSeconds: number;
            /** Format: int64 */
            paymentDurationSeconds: number;
            highestBid?: components["schemas"]["AuctionsResponse_Bid"] | null;
            /** @description How many distinct players have bid. Names nobody. */
            bidderCount: number;
        };
        AuctionsResponse_Bid: {
            bidder: components["schemas"]["PlayerRef"];
            amount: number;
            /** Format: date-time */
            bidTime: string;
        };
        OwnersLeaderboardResponse: {
            page: number;
            pageSize: number;
            /** @description How many distinct players hold at least one plot. */
            totalCount: number;
            totalPages: number;
            owners: components["schemas"]["OwnersLeaderboardResponse_Entry"][];
        };
        OwnersLeaderboardResponse_Entry: {
            /** @description The row's 1-based position across the whole leaderboard, not within the page, so page 2 at pageSize 10 starts at 11. */
            rank: number;
            player: components["schemas"]["PlayerRef"];
            plotCount: number;
        };
        StatsResponse: {
            regions: number;
            freehold: components["schemas"]["StatsResponse_Freehold"];
            leasehold: components["schemas"]["StatsResponse_Leasehold"];
            activeOffers: number;
            activeAuctions: number;
        };
        StatsResponse_Freehold: {
            contracts: number;
            /** @description Freehold contracts that currently have a title holder. */
            occupied: number;
            averagePrice: number;
        };
        StatsResponse_Leasehold: {
            contracts: number;
            /** @description Leasehold contracts that currently have a tenant. */
            occupied: number;
            averagePrice: number;
            /**
             * Format: int64
             * @description The mean lease term, in whole seconds.
             */
            averageDurationSeconds: number;
        };
        /** @description A tag id in use, and how many regions carry it. */
        TagResponse: {
            id: string;
            regionCount: number;
        };
        ResourcePackResponse: {
            /**
             * @description Every pack the renderer should texture previews with, **highest priority first**. Empty when the server configures none, which is the default.
             *
             *     A list rather than one pack because a pack is usually authored to sit on top of another. The pack a server sends to the game client overrides the client's own copy of the game, so alone in a browser it draws almost nothing; a base pack listed beneath it supplies what the client would have had. A renderer merges the list and resolves a texture two packs both provide in favour of the earlier one.
             */
            packs: components["schemas"]["ResourcePackEntry"][];
            /** @description Reserved; always null. A browser has nothing to verify a pack against, so no hash is configured or reported. */
            hash: string | null;
            /** @description Reserved; always false. A preview cannot compel a download. */
            required: boolean;
        };
        /** @description One resource pack, and the credits its own licence asks for. */
        ResourcePackEntry: {
            /** @description Where the browser fetches this pack. */
            url: string;
            /**
             * @description Credits for **this** pack, to render wherever its textures are used and nowhere else. Empty when the operator configures none.
             *
             *     Per pack rather than per server: two packs may be licensed differently, and a credit shown against the wrong one credits the wrong author. Configured beside the pack's URL in the query-service module, because the operator who picks a pack is the one who knows what its licence asks for -- splitting the two across two files on two hosts is how one of them goes stale.
             */
            attribution: components["schemas"]["ResourcePackAttribution"][];
        };
        /** @description One credit line for the resource pack. */
        ResourcePackAttribution: {
            /** @description The credit, rendered as text and never as markup. */
            text: string;
            /** @description Where the credit links, or null for plain text. Always an absolute http(s) URL -- the module rejects anything else at startup, and a client should re-check rather than trust it, since the value is operator-supplied and ends up in a page. */
            url: string | null;
        };
        ErrorResponse: {
            /** @description A stable, machine-readable error code (e.g. `WORLD_NOT_FOUND`). */
            error: string;
            /** @description A human-readable message. Never the raw text of an internal exception. */
            message: string;
        };
        /** @description The region payload, mirroring what `/realty info` renders. */
        RegionResponse: {
            worldGuardRegionId: string;
            world: components["schemas"]["WorldRef"];
            state?: string | null;
            freehold?: components["schemas"]["RegionResponse_Freehold"] | null;
            leasehold?: components["schemas"]["RegionResponse_Leasehold"] | null;
            auction?: components["schemas"]["RegionResponse_Auction"] | null;
            dimensions?: components["schemas"]["Dimensions"] | null;
            tags: string[];
        };
        RegionResponse_Freehold: {
            titleHolder?: components["schemas"]["PlayerRef"] | null;
            authority: components["schemas"]["PlayerRef"];
            /** @description Null means the region is not currently for sale. */
            price?: number | null;
            lastSoldPrice?: number | null;
            /** @description Whether the title holder is currently taking offers on this plot. */
            acceptingOffers: boolean;
        };
        RegionResponse_Leasehold: {
            landlord: components["schemas"]["PlayerRef"];
            tenant?: components["schemas"]["PlayerRef"] | null;
            price: number;
            /** Format: int64 */
            durationSeconds: number;
            /** Format: date-time */
            startDate?: string | null;
            /** Format: date-time */
            endDate?: string | null;
            extensionsUsed?: number | null;
            /** @description Null means unlimited extensions. */
            maxExtensions?: number | null;
            /**
             * Format: date-time
             * @description Null unless a party has given notice. The lease still runs until this date, so a consumer should read it as "ending", not "ended".
             */
            terminationEffectiveDate?: string | null;
            /** @description Which party gave notice. Null alongside a null terminationEffectiveDate. */
            terminatedByRole?: string | null;
            /** @description Whether the landlord is currently taking a new tenant. */
            acceptingTenants: boolean;
        };
        RegionResponse_Auction: {
            /** Format: date-time */
            endDate?: string | null;
            highestBid?: components["schemas"]["RegionResponse_Bid"] | null;
            auctioneer: components["schemas"]["PlayerRef"];
            /** Format: date-time */
            startDate: string;
            minBid: number;
            /** @description The smallest amount by which a new bid must beat the standing one. */
            minStep: number;
            /**
             * Format: int64
             * @description How long bidding stays open past the last bid. `endDate` is this added to the last bid's time, or to `startDate` when nobody has bid.
             */
            biddingDurationSeconds: number;
            /**
             * Format: int64
             * @description How long the winner then has to pay.
             */
            paymentDurationSeconds: number;
        };
        RegionResponse_Bid: {
            bidder: components["schemas"]["PlayerRef"];
            amount: number;
        };
        /** @description A region's WorldGuard geometry. Null when the query-service module is disabled or unreachable. */
        Dimensions: {
            /** @enum {string} */
            shape: "CUBOID" | "POLYGONAL";
            minY: number;
            maxY: number;
            points: components["schemas"]["Dimensions_Point"][];
        } | null;
        Dimensions_Point: {
            x: number;
            z: number;
        };
        /** @description The response for GET /v1/players/regions. When category=owned or category=rented was requested, `regions` carries that category's entries and `owned`/`landlord`/`rented` are omitted (not serialised as null). When category=all (the default), `owned`, `landlord` and `rented` are populated instead and `regions` is omitted. See the endpoint description for the shared-offset paging behaviour of category=all. */
        PlayerRegionsResponse: {
            player: components["schemas"]["PlayerRef"];
            page: number;
            pageSize: number;
            totalCount: number;
            totalPages: number;
            owned?: components["schemas"]["PlayerRegionsResponse_RegionRef"][];
            landlord?: components["schemas"]["PlayerRegionsResponse_RegionRef"][];
            rented?: components["schemas"]["PlayerRegionsResponse_RentedRef"][];
            /** @description Present only for a single-category request (category=owned or category=rented); its entries are RegionRef or RentedRef shaped per that category. */
            regions?: unknown[];
        };
        PlayerRegionsResponse_RegionRef: {
            worldGuardRegionId: string;
            world: components["schemas"]["WorldRef"];
        };
        PlayerRegionsResponse_RentedRef: {
            worldGuardRegionId: string;
            world: components["schemas"]["WorldRef"];
            /** Format: date-time */
            endDate?: string | null;
            /** Format: int64 */
            secondsRemaining?: number | null;
        };
        /** @description A page of search results. `results` is empty rather than absent when nothing matched. */
        SearchResponse: {
            page: number;
            pageSize: number;
            totalCount: number;
            totalPages: number;
            results: components["schemas"]["SearchResponse_Result"][];
        };
        /** @description One matching region, as the search projection reports it. Deliberately minimal -- a browse listing shows identity, type and price, and fetches `/v1/regions` for the row a user opens. */
        SearchResponse_Result: {
            worldGuardRegionId: string;
            world: components["schemas"]["WorldRef"];
            /** @enum {string} */
            contractType: "freehold" | "leasehold";
            /** @description The asking price, or null for a freehold that is not currently for sale. Null only appears under `type=freehold`. */
            price: number | null;
            /**
             * @description Never null here: a search result matched on a contract, so it always has a state. Contrast `/v1/regions`, which lists contractless regions too and reports null for them.
             * @enum {string}
             */
            state: "FOR_SALE" | "SOLD" | "FOR_LEASE" | "LEASED";
            /**
             * Format: int64
             * @description The lease term the price buys, in seconds. Null for a freehold, whose price is a one-off. Carried here because a rent without its term is a number without a unit, and a listing should not have to fetch every region to say what its price means.
             */
            durationSeconds: number | null;
        };
        /** @description A page of registered regions. Entries carry identity only; `/v1/region` returns a single region's contracts, auction and tags. */
        RegionListResponse: {
            page: number;
            pageSize: number;
            totalCount: number;
            totalPages: number;
            regions: components["schemas"]["RegionListResponse_Entry"][];
        };
        RegionListResponse_Entry: {
            worldGuardRegionId: string;
            world: components["schemas"]["WorldRef"];
            /** @description The region's state, so a browse grid need not call `/v1/region` once per row to learn it. Null for a registered region carrying no contract at all -- which `/v1/regions` lists and `/v1/regions/search` does not. */
            state: string | null;
        };
        RegionsAtResponse: {
            /**
             * @description Which question was answered. `point` when the request carried a `y`, `column` when it did not.
             * @enum {string}
             */
            test: "point" | "column";
            regions: components["schemas"]["RegionsAtResponse_Entry"][];
        };
        RegionsAtResponse_Entry: {
            worldGuardRegionId: string;
            world: components["schemas"]["WorldRef"];
        };
        RegionMembersResponse: {
            owners: components["schemas"]["RegionMembersResponse_Party"];
            members: components["schemas"]["RegionMembersResponse_Party"];
        };
        /** @description One WorldGuard domain, with its three kinds of entry kept apart because WorldGuard stores three kinds and flattening them loses information. */
        RegionMembersResponse_Party: {
            /** @description UUID entries, with a name where the module could supply one. */
            players: components["schemas"]["PlayerRef"][];
            /** @description Legacy name entries, which carry no UUID and so cannot be a PlayerRef. WorldGuard lower-cases these on the way in and they are reported as it holds them. */
            playerNames: string[];
            /** @description Permission group names, which are not players. */
            groups: string[];
        };
        WorldGeometryResponse: {
            page: number;
            pageSize: number;
            totalCount: number;
            totalPages: number;
            world: components["schemas"]["WorldRef"];
            regions: components["schemas"]["WorldGeometryResponse_Entry"][];
        };
        WorldGeometryResponse_Entry: {
            worldGuardRegionId: string;
            /** @description Null when the query-service module is disabled or unreachable, or when Realty has the region registered but WorldGuard no longer holds it. The row is still reported in either case. */
            dimensions: components["schemas"]["Dimensions"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is up and the database is reachable. `module` reports the query-service module's own status separately -- an unreachable module is a degraded enrichment source, not an unhealthy service, so it never turns this response into a 503. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /** @enum {string} */
                        module: "ok" | "unreachable" | "disabled";
                    };
                };
            };
            /** @description The database could not be reached. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "degraded";
                    };
                };
            };
        };
    };
    listWorlds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The full list of known worlds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldRef"][];
                };
            };
        };
    };
    getRegion: {
        parameters: {
            query: {
                /** @description A world's UUID or its name. A world name is a folder name on disk and may contain spaces or other characters requiring percent-encoding (for example `My World` becomes `My%20World`, or `+` may be used in place of a space) -- send the raw name percent-encoded, do not pre-decode it. */
                world: string;
                /** @description The WorldGuard region id, exactly as WorldGuard stores it. */
                region: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The region's current state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionResponse"];
                };
            };
            /** @description `MISSING_PARAMETER` when `world` or `region` is absent or blank. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `WORLD_NOT_FOUND` when `world` names no known world; `REGION_NOT_FOUND` when the region does not exist in that world. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `INTERNAL_ERROR` -- a generic message only, never the underlying exception. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRegionHistory: {
        parameters: {
            query: {
                /** @description A world name or UUID. */
                world: string;
                /** @description The WorldGuard region id. */
                region: string;
                /** @description Restrict to one event type. Case-insensitive; an unrecognised value is rejected rather than ignored, so a typo does not silently return everything. */
                type?: "BUY" | "AUCTION_BUY" | "OFFER_BUY" | "AGENT_ADD" | "AGENT_REMOVE" | "RENT" | "UNRENT" | "RENEW" | "LEASEHOLD_EXPIRY" | "SET_PRICE" | "UNSET_PRICE" | "SET_TITLEHOLDER" | "UNSET_TITLEHOLDER" | "SET_DURATION" | "SET_LANDLORD" | "SET_TENANT" | "UNSET_TENANT" | "SET_MAX_EXTENSIONS" | "MODIFY_PROPOSE" | "MODIFY_ACCEPT" | "MODIFY_REJECT" | "MODIFY_WITHDRAW" | "MODIFY_APPLY" | "TERMINATE" | "TERMINATION_CANCEL";
                /** @description Only events at or after this instant. Must carry an offset (`Z` or `+hh:mm`): a bare local date-time is rejected rather than assumed to be UTC, since assuming would shift a caller's window by hours in silence. The command takes a relative duration instead; `now - duration` is a trivial conversion on the client. */
                since?: string;
                /** @description Only events this player took part in, given as a UUID or a name. A UUID needs no module; a name is resolved through the query-service module, so it answers 404 for an unknown name and 502 when the module is unreachable. Omit to not filter by player. */
                player?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested page of events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description `MISSING_PARAMETER`, `INVALID_EVENT_TYPE`, `INVALID_SINCE`, `MALFORMED_UUID` (a UUID-shaped `player` that does not parse), `INVALID_PAGE` or `INVALID_PAGE_SIZE`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `WORLD_NOT_FOUND` -- Realty has never seen that world. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `INTERNAL_ERROR` -- a generic message only, never the underlying exception. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listRegions: {
        parameters: {
            query?: {
                /** @description 1-based page number. Defaults to 1. */
                page?: number;
                /** @description Page size, clamped to the server's configured maximum, which is itself capped at 100. Defaults to 10 (or the configured maximum if it is lower). A larger value is clamped rather than rejected. */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested page. An empty `regions` array means no region is registered, or the page lies beyond the last one. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionListResponse"];
                };
            };
            /** @description `INVALID_PAGE` or `INVALID_PAGE_SIZE` for a non-integer or out-of-range value. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `INTERNAL_ERROR` -- a generic message only, never the underlying exception. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    searchRegions: {
        parameters: {
            query?: {
                /** @description Which contracts to search. `sale` is freeholds with an asking price, `rent` is leaseholds, and `all` (the default) is both -- the market view, matching the in-game `/realty search`. `freehold` widens to every freehold contract, including sold or never-listed regions, which come back with a null `price`; the price bounds apply only to the priced rows, since an unpriced one has nothing to compare. `leasehold` is every leasehold contract, which is the same set as `rent` because a lease always carries a price. */
                type?: "sale" | "rent" | "all" | "freehold" | "leasehold";
                /** @description Restricts results to one world, given as a UUID or a name. A world name is a folder name on disk and may contain spaces or other characters requiring percent-encoding -- send the raw name percent-encoded, do not pre-decode it. Omit to search every world. */
                world?: string;
                /** @description Inclusive lower price bound. Defaults to no lower bound. */
                minPrice?: number;
                /** @description Inclusive upper price bound. Defaults to no upper bound. */
                maxPrice?: number;
                /** @description Repeatable. A region matches when it carries at least one of the given tags. Omit for no tag filter. */
                tag?: string[];
                /** @description `unoccupied` restricts to regions with no titleholder or tenant, `occupied` to those with one, `any` (the default) does not filter. */
                occupancy?: "any" | "occupied" | "unoccupied";
                /** @description Result order. Defaults to most expensive first. */
                sort?: "price_desc" | "price_asc";
                /** @description 1-based page number. Defaults to 1. */
                page?: number;
                /** @description Page size, clamped to the server's configured maximum, which is itself capped at 100. Defaults to 10 (or the configured maximum if it is lower). A larger value is clamped rather than rejected. */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested page of matching regions. An empty `results` array means nothing matched. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description `INVALID_TYPE`, `INVALID_OCCUPANCY` or `INVALID_SORT` when that parameter is present but not one of its listed values; `INVALID_PRICE` when `minPrice` or `maxPrice` is not a finite number, is negative, or `minPrice` exceeds `maxPrice`; `INVALID_PAGE` or `INVALID_PAGE_SIZE` for a non-integer or out-of-range value. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `WORLD_NOT_FOUND` when `world` names no known world. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `INTERNAL_ERROR` -- a generic message only, never the underlying exception. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getActivity: {
        parameters: {
            query?: {
                /** @description Repeatable. Restrict the feed to these event types. Omitted entirely, the default ticker set applies; an unrecognised value is rejected rather than ignored. */
                type?: string[];
                /** @description Narrow to one world, by name or UUID. */
                world?: string;
                /** @description Only events at or after this instant. Must carry an offset; a bare local date-time is rejected rather than assumed to be UTC. */
                since?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested page of events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            /** @description `INVALID_EVENT_TYPE`, `INVALID_SINCE`, `INVALID_PAGE` or `INVALID_PAGE_SIZE`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `WORLD_NOT_FOUND` -- Realty has never seen that world. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `INTERNAL_ERROR` -- a generic message only, never the underlying exception. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listAuctions: {
        parameters: {
            query?: {
                /** @description Narrow to one world, by name or UUID. Omitted lists every world. */
                world?: string;
                /** @description `ending_soon` (default) orders by the bidding deadline, soonest first. `highest_bid` orders by the standing bid, largest first, with an auction nobody has bid on ranking at its minimum bid. */
                sort?: "ending_soon" | "highest_bid";
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested page. An empty `auctions` array means nothing is under the hammer, or the page lies beyond the last one. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuctionsResponse"];
                };
            };
            /** @description `INVALID_SORT`, `INVALID_PAGE` or `INVALID_PAGE_SIZE`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `WORLD_NOT_FOUND` -- Realty has never seen that world. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `INTERNAL_ERROR` -- a generic message only, never the underlying exception. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOwnersLeaderboard: {
        parameters: {
            query?: {
                /** @description 1-based page number. Defaults to 1. */
                page?: number;
                /** @description Page size, clamped to the server's configured maximum, which is itself capped at 100. Defaults to 10. */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested page. An empty `owners` array means nobody holds a plot, or the page lies beyond the last one. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnersLeaderboardResponse"];
                };
            };
            /** @description `INVALID_PAGE` or `INVALID_PAGE_SIZE`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `INTERNAL_ERROR` -- a generic message only, never the underlying exception. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current totals. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description `INTERNAL_ERROR` -- a generic message only, never the underlying exception. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every tag in use, in the order the backend reports them. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"][];
                };
            };
            /** @description `INTERNAL_ERROR` -- a generic message only, never the underlying exception. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    regionsAt: {
        parameters: {
            query: {
                /** @description The world, as a UUID or a name. */
                world: string;
                /** @description Block X coordinate. */
                x: number;
                /** @description Block Z coordinate. */
                z: number;
                /** @description Block Y coordinate. Omit for a column test. An empty value is treated as omitted, so a client templating the query string with nothing to substitute asks the column question rather than getting a 400. */
                y?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The regions covering that block, in WorldGuard's own region order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionsAtResponse"];
                };
            };
            /** @description `MISSING_PARAMETER` when `world` is absent, or `INVALID_COORDINATE` when `x` or `z` is absent, or any of the three is not a whole number. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `WORLD_NOT_FOUND` -- no world of that name or id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `INTERNAL_ERROR` -- a generic message only, never the underlying exception. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `GEOMETRY_UNAVAILABLE` -- the query-service module is disabled or unreachable, and this route has no database-only answer to fall back on. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    regionMembers: {
        parameters: {
            query: {
                /** @description The world, as a UUID or a name. */
                world: string;
                /** @description The WorldGuard region id. */
                region: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Both domains. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionMembersResponse"];
                };
            };
            /** @description `MISSING_PARAMETER` -- `world` or `region` was not given. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `WORLD_NOT_FOUND`, or `REGION_NOT_FOUND` when Realty does not manage that region or WorldGuard no longer holds it. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `INTERNAL_ERROR` -- a generic message only, never the underlying exception. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `MEMBERS_UNAVAILABLE` -- the query-service module is disabled or unreachable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    regionSchematic: {
        parameters: {
            query: {
                /** @description The world, as a UUID or a name. */
                world: string;
                /** @description The WorldGuard region id. */
                region: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The schematic bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description `MISSING_PARAMETER` -- `world` or `region` was not given. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `WORLD_NOT_FOUND`, or `SCHEMATIC_NOT_FOUND` when the region has never been captured. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `INTERNAL_ERROR` -- a generic message only, never the underlying exception. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resourcePack: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The configured pack, or nulls when none is set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourcePackResponse"];
                };
            };
            /** @description `INTERNAL_ERROR` -- a generic message only, never the underlying exception. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `RESOURCE_PACK_UNAVAILABLE` -- the query-service module is disabled or unreachable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    worldGeometry: {
        parameters: {
            query: {
                /** @description The world, as a UUID or a name. */
                world: string;
                /** @description 1-based page number. Defaults to 1. */
                page?: number;
                /** @description Rows per page, defaulting to 10 and clamped to the operator's configured maximum. */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the world's registered regions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldGeometryResponse"];
                };
            };
            /** @description `MISSING_PARAMETER`, `INVALID_PAGE` or `INVALID_PAGE_SIZE`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `WORLD_NOT_FOUND` -- no world of that name or id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `INTERNAL_ERROR` -- a generic message only, never the underlying exception. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listPlayerRegions: {
        parameters: {
            query: {
                /** @description The player, as a UUID or a name. A UUID is answered from the database alone, so this form keeps working while the query-service module is down -- the returned `name` is simply null, as every other module-sourced field degrades. A name is resolved through the module, so it answers 404 for an unknown name and 502 when the module is unreachable. A Floodgate (Bedrock) player's name is a `.` followed by their Xbox gamertag, which may itself contain spaces -- send it percent-encoded, so `.Some Gamertag` becomes `.Some%20Gamertag`. */
                player: string;
                /** @description One of `all` (default), `owned`, or `rented`. */
                category?: "all" | "owned" | "rented";
                /** @description 1-based page number. Defaults to 1. */
                page?: number;
                /** @description Page size, clamped to the server's configured maximum, which is itself capped at 100. Defaults to 10 (or the configured maximum if it is lower). A larger value is clamped rather than rejected. */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested page of the player's regions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRegionsResponse"];
                };
            };
            /** @description `MISSING_PARAMETER` when `player` was not given; `MALFORMED_UUID` when a UUID-shaped `player` does not parse; `INVALID_PAGE` or `INVALID_PAGE_SIZE` for a non-integer or out-of-range `page`/`pageSize`; `INVALID_CATEGORY` when `category` is present but not one of `all`, `owned`, `rented`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `PLAYER_NOT_FOUND` -- `player` names a player the server does not know. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `INTERNAL_ERROR` -- a generic message only, never the underlying exception. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `NAME_LOOKUP_UNAVAILABLE` -- `player` was given as a name and the query-service module is not reachable. Never returned for a UUID-shaped `player`, which needs no module. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPlayerSummary: {
        parameters: {
            query: {
                /** @description The player, as a UUID or a name. A UUID is answered from the database alone, so this form keeps working while the query-service module is down -- the returned `name` is simply null, as every other module-sourced field degrades. A name is resolved through the module, so it answers 404 for an unknown name and 502 when the module is unreachable. A Floodgate (Bedrock) player's name is a `.` followed by their Xbox gamertag, which may itself contain spaces -- send it percent-encoded, so `.Some Gamertag` becomes `.Some%20Gamertag`. */
                player: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The player's holdings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSummaryResponse"];
                };
            };
            /** @description `MISSING_PARAMETER` when `player` was not given, or `MALFORMED_UUID` when a UUID-shaped `player` does not parse. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `PLAYER_NOT_FOUND` -- the module knows no player by that name. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `INTERNAL_ERROR` -- a generic message only, never the underlying exception. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `NAME_LOOKUP_UNAVAILABLE` -- `player` was given as a name and the module is unreachable. Never returned for a UUID-shaped `player`, which needs no module. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    lookupPlayer: {
        parameters: {
            query: {
                /** @description The player name to resolve. Percent-encode a name containing a space; a Floodgate player is its gamertag behind a leading `.`. This route always takes a name -- resolving a UUID you already hold has no purpose -- so it keeps its own parameter name rather than the `player` every other player-scoped route takes, which accepts either. */
                playerName: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The resolved player. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRef"];
                };
            };
            /** @description `MISSING_PARAMETER` -- `playerName` was absent or blank. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `PLAYER_NOT_FOUND` -- the module knows no player by that name. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `INTERNAL_ERROR` -- a generic message only, never the underlying exception. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `NAME_LOOKUP_UNAVAILABLE` -- the query-service module is disabled or unreachable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOpenApiYaml: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
    getOpenApiJson: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    getDocs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Swagger UI HTML page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
}
