package io.github.md5sha256.realty.api;

public enum HistoryEventType {
    BUY,
    AUCTION_BUY,
    OFFER_BUY,
    AGENT_ADD,
    AGENT_REMOVE,
    RENT,
    UNRENT,
    RENEW,
    LEASEHOLD_EXPIRY,
    SET_PRICE,
    UNSET_PRICE,
    SET_TITLEHOLDER,
    UNSET_TITLEHOLDER,
    SET_DURATION,
    SET_LANDLORD,
    SET_TENANT,
    UNSET_TENANT,
    SET_MAX_EXTENSIONS,
    MODIFY_PROPOSE,
    MODIFY_ACCEPT,
    MODIFY_REJECT,
    MODIFY_WITHDRAW,
    MODIFY_APPLY,
    TERMINATE,
    TERMINATION_CANCEL
}
